[package]
name = "recorder_persist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
compact_str.workspace = true
itertools.workspace = true
parquet.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
